### ISSUE TITLE
Implement quotas and docker rootless per user

### ISSUE THREAD

**Issue by stefanpejcic** [stefanpejcic/OpenPanel#301]
### OpenPanel version(s) affected

0.4.0

### What OS are you using?

Ubuntu

### Description

Currently, we create one container per user as root, with two separate limits:

- **storage_file**: This limit applies to the space allocated for the `/home/USERNAME/` directory, which contains all the user's website and email files.
- **storage**: This is the limit for the Docker container itself, which cannot be adjusted after creation.

Having these two separate limits is confusing for users. Additionally, we are unable to increase the storage limit and cannot decrease the **storage_file** limit.

To simplify, we could implement quotas on the `/home/USERNAME/` folders for each user. By enabling Docker's rootless mode, we can store the container files in `/home/USERNAME/.containers/`, meaning the container's size will be virtually unlimited, but it will still inherit the user's quota. This approach allows both upgrading and downgrading the storage and simplifies to having just one limit per user.

### How to reproduce

this resolves:

- [x] [Resize docker container #56](https://github.com/stefanpejcic/OpenPanel/issues/56) - as we can downgrade and upgrade the container size by simply changing quota for user
- [ ] [Can not change docker mount point when user is renamed #196](https://github.com/stefanpejcic/OpenPanel/issues/196)
- [ ]  as even when user is renamed, contianer paths remain relative
- [x]  [Inode limits aren't displayed properly #243](https://github.com/stefanpejcic/OpenPanel/issues/243) - it will display just the quota file number limits
- [x] [Package resources can't be updated #293](https://github.com/stefanpejcic/OpenPanel/issues/293) - this will also be possible
- [x]  faster install - no storage space is needed
- [x] no need to set overlay driver for docker

### Possible Solution

problems:
- [x]  root's docker containers need to be able to reach docker networks of users
-

**Comment by stefanpejcic** [comment]
- [ ] edit nginx vhost files to use ip of containeri instead

**Comment by stefanpejcic** [comment]
todo:

- [ ] openpanel ui to run all commands for user instead of docker
- [ ] openadmin ui to run all commands for user instead of docker
- [ ] opencli to run all commands for user instead of docker
- [ ] install script to be rewritten
- [ ]
